### PR TITLE
Tolerance fix for interval solvers

### LINKED ISSUE #57: abstol and reltol are ignored
`abstol` and `reltol` keyword arguments seem to be ignored. 

```
julia> using SimpleNonlinearSolve

julia> f(u, p) = u^4 .- 2.0
julia> prob = IntervalNonlinearProblem(f, (1.0, 2.0))

julia> sol = solve(probB, Brent())  # full precision
u: 1.1892071150027212

julia> sol = solve(prob, Brent(), maxiters=3) # maxiters works
u: 1.0666666666666667

julia> sol = solve(prob, Brent(), abstol=0.1)  # abstol is ignored and gives the maximum precision
u: 1.1892071150027212
```

More fundamental problem perhaps is that there are apparently no tests for abstol and reltol ?

### PR DESCRIPTION
**Pull request by yash2798**
fixes #57

### CODE REVIEW

File: src/bisection.jl [hunk 1]
```diff
@@ -46,6 +46,11 @@ function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Bisection, args...
                     retcode = ReturnCode.FloatingPointLimit,
                     left = left, right = right)
             fm = f(mid)
+            if abs((right - left) / 2) < atol
+                return SciMLBase.build_solution(prob, alg, mid, fm;
+                    retcode = ReturnCode.Success,
```
Comment (yash2798) [inline src/bisection.jl:51]: @ChrisRackauckas in case of tolerance reached, we would naturally return the 'Success' retcode, right?

Comment (ChrisRackauckas) [reply src/bisection.jl:51]: yes

File: src/bisection.jl [hunk 2]
```diff
@@ -31,6 +31,11 @@ function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Bisection, args...
             retcode = ReturnCode.ExactSolutionLeft, left = left,
             right = right)
     end
+    if iszero(fr)
```
Comment (yash2798) [inline src/bisection.jl:34]: Also, i dont see `RightExactSolution` condition in any of these bracketing solvers, was that intentional? Otherwise, it's gonna calculate an inexact solution even if the right value is the exact zero?

Comment (ChrisRackauckas) [reply src/bisection.jl:34]: If there is a condition by which right solution is exact it should do that retcode yes.

**Comment by yash2798** [comment]
@ChrisRackauckas this can be reviewed now

File: src/bisection.jl [hunk 3]
```diff
@@ -20,17 +20,22 @@ function Bisection(; exact_left = false, exact_right = false)
...
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Bisection, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
     kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     left, right = prob.tspan
     fl, fr = f(left), f(right)
-
+    atol = abstol !== nothing ? abstol : eps(1.0)
```
Comment (ChrisRackauckas) [inline src/bisection.jl:28]:
```suggestion
    atol = abstol !== nothing ? abstol : eps(left)
```

File: src/brent.jl [hunk 4]
```diff
@@ -7,17 +7,22 @@ A non-allocating Brent method
...
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Brent, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
     kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     a, b = prob.tspan
     fa, fb = f(a), f(b)
     ϵ = eps(convert(typeof(fa), 1.0))
+    atol = abstol !== nothing ? abstol : eps(1.0)
```
Comment (ChrisRackauckas) [inline src/brent.jl:16]:
```suggestion
    atol = abstol !== nothing ? abstol : minimum(eps(left), eps(right))
```

File: src/falsi.jl [hunk 5]
```diff
@@ -4,16 +4,21 @@
 struct Falsi <: AbstractBracketingAlgorithm end
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Falsi, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
     kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     left, right = prob.tspan
     fl, fr = f(left), f(right)
+    atol = abstol !== nothing ? abstol : eps(1.0)
```
Comment (ChrisRackauckas) [inline src/falsi.jl:12]:
```suggestion
    atol = abstol !== nothing ? abstol : minimum(eps(left), eps(right))
```

File: src/ridder.jl [hunk 6]
```diff
@@ -7,16 +7,21 @@ A non-allocating ridder method
 struct Ridder <: AbstractBracketingAlgorithm end
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Ridder, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
     kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     left, right = prob.tspan
     fl, fr = f(left), f(right)
+    atol = abstol !== nothing ? abstol : eps(1.0)
```
Comment (ChrisRackauckas) [inline src/ridder.jl:15]:
```suggestion
    atol = abstol !== nothing ? abstol : minimum(eps(left), eps(right))
```

File: src/bisection.jl [hunk 7]
```diff
@@ -20,17 +20,22 @@ function Bisection(; exact_left = false, exact_right = false)
...
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Bisection, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
     kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     left, right = prob.tspan
     fl, fr = f(left), f(right)
-
+    atol = abstol !== nothing ? abstol : minimum(eps(left), eps(right))
```
Comment (ChrisRackauckas) [inline src/bisection.jl:28]:
```suggestion
    atol = abstol !== nothing ? abstol : min(eps(left), eps(right))
```

File: src/brent.jl [hunk 8]
```diff
@@ -7,17 +7,22 @@ A non-allocating Brent method
...
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Brent, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
     kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     a, b = prob.tspan
     fa, fb = f(a), f(b)
     ϵ = eps(convert(typeof(fa), 1.0))
+    atol = abstol !== nothing ? abstol : minimum(eps(left), eps(right))
```
Comment (ChrisRackauckas) [inline src/brent.jl:16]:
```suggestion
    atol = abstol !== nothing ? abstol : min(eps(left), eps(right))
```

File: src/falsi.jl [hunk 9]
```diff
@@ -4,16 +4,21 @@
 struct Falsi <: AbstractBracketingAlgorithm end
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Falsi, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
     kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     left, right = prob.tspan
     fl, fr = f(left), f(right)
+    atol = abstol !== nothing ? abstol : minimum(eps(left), eps(right))
```
Comment (ChrisRackauckas) [inline src/falsi.jl:12]:
```suggestion
    atol = abstol !== nothing ? abstol : min(eps(left), eps(right))
```

File: src/ridder.jl [hunk 10]
```diff
@@ -7,16 +7,21 @@ A non-allocating ridder method
 struct Ridder <: AbstractBracketingAlgorithm end
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Ridder, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
     kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     left, right = prob.tspan
     fl, fr = f(left), f(right)
+    atol = abstol !== nothing ? abstol : minimum(eps(left), eps(right))
```
Comment (ChrisRackauckas) [inline src/ridder.jl:15]:
```suggestion
    atol = abstol !== nothing ? abstol : min(eps(left), eps(right))
```

**Comment by ChrisRackauckas** [comment]
Why isn't ITP in this list?

**Comment by yash2798** [comment]
> Why isn't ITP in this list?

sorry, just added it. i was under the impression that it was already there as we had an epsilon in the algorithm, but the early exit condition wasnt there.

File: src/itp.jl [hunk 11]
```diff
@@ -59,12 +59,12 @@ struct ITP{T} <: AbstractBracketingAlgorithm
...
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::ITP,
-    args...; abstol = 1.0e-15,
+    args...; abstol = nothing,
     maxiters = 1000, kwargs...)
     f = Base.Fix2(prob.f, prob.p)
     left, right = prob.tspan # a and b
     fl, fr = f(left), f(right)
-    ϵ = abstol
+    ϵ = abstol !== nothing ? abstol : min(eps(left), eps(right))
```
Comment (ChrisRackauckas) [inline src/itp.jl:67]: Why is this not just done in the keyword argument to make it cleaner?

File: src/itp.jl [hunk 12]
```diff
@@ -59,12 +59,12 @@ struct ITP{T} <: AbstractBracketingAlgorithm
 end
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::ITP,
-    args...; abstol = 1.0e-15,
+    args...; abstol = nothing,
```
Comment (ChrisRackauckas) [inline src/itp.jl:62]:
```suggestion
    args...; abstol = min(eps(prob.tspan.left), eps(prob.tspan.right)),
```

File: src/falsi.jl [hunk 13]
```diff
@@ -4,16 +4,21 @@
 struct Falsi <: AbstractBracketingAlgorithm end
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Falsi, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
```
Comment (ChrisRackauckas) [inline src/falsi.jl:7]:
```suggestion
    maxiters = 1000, abstol = min(eps(prob.tspan.left), eps(prob.tspan.right)),
```

File: src/brent.jl [hunk 14]
```diff
@@ -7,17 +7,22 @@ A non-allocating Brent method
 struct Brent <: AbstractBracketingAlgorithm end
 
 function SciMLBase.solve(prob::IntervalNonlinearProblem, alg::Brent, args...;
-    maxiters = 1000,
+    maxiters = 1000, abstol = nothing,
```
Comment (ChrisRackauckas) [inline src/brent.jl:10]:
```suggestion
    maxiters = 1000, abstol = min(eps(prob.tspan.left), eps(prob.tspan.right)),
```

File: src/itp.jl (hunk 11 above)
Comment (yash2798) [reply src/itp.jl]: yes this can be done to make the code cleaner. made the changes
